/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

type ArrayOf<T> = Array<
  T & {
    _key: string
  }
>

// Source: schema.json
export type ContentBlock = {
  contentType?: 'mainPortableText' | 'faq'
  portableTextBlock?: MainPortableText
  faq?: Faq
}

export type SuccessStoriesBlock = {
  _type: 'successStoriesBlock'
  backgroundColor?: 'yellow' | 'orange' | 'lightBlue' | 'navy'
  stories?: Array<
    {
      _key: string
    } & SimplePortableText
  >
  disabled?: boolean
}

export type SingleColumnContentBlock = {
  _type: 'singleColumnContentBlock'
  title?: string
  backgroundColor?: '#ffffff' | '#e2e2e2' | '#61c8e9' | '#013b63' | '#feca2d'
  removeBottomPadding?: boolean
  skinny?: boolean
  centerContent?: boolean
  contentBlock?: ContentBlock
  disabled?: boolean
}

export type RowContainer = {
  _type: 'rowContainer'
  title?: string
  hideTitle?: boolean
  centerTitle?: boolean
  titleColor?: '#333333' | '#16abcc' | '#ee6d08' | '#feca2d' | '#ffffff'
  row?: 'twoColumn' | 'threeColumn'
  removeBottomPadding?: boolean
  condensedCopy?: boolean
  centerCopy?: boolean
  image?: MainImage
  overlay?: 'noOverlay' | 'darkOverlay' | 'blueOverlay'
  backgroundColor?: '#ffffff' | '#e2e2e2' | '#16abcc' | '#ee6d08' | '#feca2d'
  rowContent?: Array<
    | ({
        _key: string
      } & AcuityForm)
    | ({
        _key: string
      } & Carousel)
    | ({
        _key: string
      } & Form)
    | ({
        _key: string
      } & IconCard)
    | ({
        _key: string
      } & MainImage)
    | ({
        _key: string
      } & ImageButtonCard)
    | ({
        _key: string
      } & MainPortableText)
    | ({
        _key: string
      } & Faq)
  >
  disabled?: boolean
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type ResourceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'resource'
}

export type RelatedResourcesRow = {
  _type: 'relatedResourcesRow'
  title?: string
  titleColor?: '#ee6d08' | '#333333' | '#16abcc' | '#feca2d' | '#ffffff'
  backgroundColor?: '#e2e2e2' | '#ffffff' | '#16abcc' | '#ee6d08' | '#feca2d'
  relatedResources?: ArrayOf<PostReference | ResourceReference>
  disabled?: boolean
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type ClassReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'class'
}

export type SimplePortableText = {
  _type: 'simplePortableText'
  portableTextBlock?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      | {
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }
      | {
          item?: PageReference | ClassReference
          _type: 'internalLink'
          _key: string
        }
    >
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type MainPortableText = {
  _type: 'mainPortableText'
  portableTextBlock?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              href?: string
              blank?: boolean
              _type: 'link'
              _key: string
            }
          | {
              item?: PageReference | ClassReference
              _type: 'internalLink'
              _key: string
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & Cta)
    | ({
        _key: string
      } & Youtube)
    | {
        hr?: string
        size?: string
        width?: string
        _type: 'hr'
        _key: string
      }
    | ({
        _key: string
      } & LogoRow)
    | ({
        _key: string
      } & ContactInfo)
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        _type: 'image'
        _key: string
      }
  >
}

export type Youtube = {
  _type: 'youtube'
  url?: string
}

export type MainImage = {
  _type: 'mainImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  width?: number
  height?: number
  alt?: string
}

export type LogoRow = {
  _type: 'logoRow'
  logoRow?: Array<
    {
      _key: string
    } & Logo
  >
}

export type Logo = {
  _type: 'logo'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  logo?: string
  alt: string
}

export type Icon = {
  _type: 'icon'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt: string
}

export type HeroTwoPanel = {
  _type: 'heroTwoPanel'
  size?: 'standard' | 'x-large'
  image?: MainImage
  backgroundColor?: '#16abcc' | '#ee6d08' | '#feca2d' | '#ffffff' | '#323943'
  mainPortableText?: MainPortableText
  centerText?: boolean
  disabled?: boolean
}

export type HeroBanner = {
  _type: 'heroBanner'
  size?: 'standard' | 'x-large'
  subheading?: string
  subHeadingColor?: 'white' | 'orange' | 'blue' | 'yellow' | 'grey33'
  heading: string
  headingColor?: 'white' | 'orange' | 'blue' | 'yellow' | 'grey33'
  copy?: SimplePortableText
  copyColor?: 'white' | 'orange' | 'blue' | 'yellow' | 'grey33'
  image?: MainImage
  overlay?: 'noOverlay' | 'darkOverlay' | 'blueOverlay'
  cta?: Cta
  disabled?: boolean
}

export type Form = {
  _type: 'form'
  title: string
  copy?: SimplePortableText
}

export type Faq = {
  _type: 'faq'
  items?: Array<{
    question: string
    answer: MainPortableText
    _type: 'faqItem'
    _key: string
  }>
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type Cta = {
  _type: 'cta'
  title?: string
  kind?: 'button' | 'link'
  arrow?: boolean
  landingPageRoute?: PageReference | PostReference
  link?: string
  anchor?: string
  fileDownload?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
}

export type Carousel = {
  _type: 'carousel'
  carouselImages?: Array<
    {
      _key: string
    } & MainImage
  >
}

export type AcuityForm = {
  _type: 'acuityForm'
  title: string
  copy?: SimplePortableText
}

export type NavDropdownCTA = {
  _type: 'navDropdownCTA'
  cta?: Cta
  subnav?: Array<
    {
      _key: string
    } & Cta
  >
}

export type NavCTA = {
  _type: 'navCTA'
  cta?: Cta
}

export type Seo = {
  _type: 'seo'
  seoTitle?: string
  seoDescription: string
  noindex?: boolean
  canonicalUrl?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type DateTimeV2 = {
  _type: 'dateTimeV2'
  dateTime: string
  acuityId?: string
  totalSpots?: number
  bookingsCount?: number
  availability?: 'open' | 'nearlyFull' | 'full'
}

export type DateTime = {
  _type: 'dateTime'
  startDate?: string
  startTime?: string
  amPm: 'am' | 'pm'
  availability?: 'open' | 'nearlyFull' | 'full'
}

export type TrainerReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'trainer'
}

export type TrainersGridContainer = {
  _type: 'trainersGridContainer'
  backgroundColor?: '#ffffff' | '#e2e2e2' | '#61c8e9' | '#feca2d'
  trainers?: Array<
    {
      _key: string
    } & TrainerReference
  >
}

export type TestimonialReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'testimonial'
}

export type TestimonialGridContainer = {
  _type: 'testimonialGridContainer'
  title?: string
  titleColor?: '#ee6d08' | '#333333' | '#16abcc' | '#feca2d' | '#ffffff'
  backgroundColor?: '#ffffff' | '#e2e2e2' | '#61c8e9' | '#feca2d'
  skinny?: boolean
  testimonialsArr?: Array<
    {
      _key: string
    } & TestimonialReference
  >
  disabled?: boolean
}

export type ProgramsGridContainer = {
  _type: 'programsGridContainer'
  backgroundColor?: '#ffffff' | '#e2e2e2' | '#61c8e9' | '#feca2d'
  programs?: Array<
    {
      _key: string
    } & ClassReference
  >
  enhanced?: boolean
  description?: MainPortableText
  centerContent?: boolean
}

export type ProductReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'product'
}

export type ProductGridContainer = {
  _type: 'productGridContainer'
  backgroundColor?: '#ffffff' | '#e2e2e2' | '#61c8e9' | '#feca2d'
  productsArr?: Array<
    {
      _key: string
    } & ProductReference
  >
  disabled?: boolean
}

export type PostsGridContainer = {
  _type: 'postsGridContainer'
  backgroundColor?: '#ffffff' | '#e2e2e2' | '#61c8e9' | '#feca2d'
  posts?: Array<
    {
      _key: string
    } & PostReference
  >
}

export type TrainerRows = {
  _type: 'trainerRows'
  trainers?: Array<
    {
      _key: string
    } & TrainerReference
  >
}

export type GalleryGrid = {
  _type: 'galleryGrid'
  galleryArr?: Array<
    {
      _key: string
    } & MainImage
  >
}

export type CustomComponent = {
  _type: 'customComponent'
  title?: string
  backgroundColor?: '#ffffff' | '#e2e2e2' | '#61c8e9' | '#feca2d' | '#ee6d08'
  rows?: Array<
    | ({
        _key: string
      } & TrainerRows)
    | ({
        _key: string
      } & GalleryGrid)
    | ({
        _key: string
      } & AboutUsContainer)
  >
  disabled?: boolean
}

export type ContactPageMap = {
  _type: 'contactPageMap'
  map: string
  mapLink: string
  copy?: MainPortableText
  iconCards?: Array<
    {
      _key: string
    } & IconCard
  >
}

export type ContactInfo = {
  _type: 'contactInfo'
  headline?: string
  phoneNumber: string
  phoneLabel?: string
  email: string
  textColor?: 'white' | 'blue'
  size?: 'normal' | 'large'
}

export type AboutUsContainer = {
  _type: 'aboutUsContainer'
  copy?: MainPortableText
  iconCards?: Array<
    {
      _key: string
    } & IconCard
  >
}

export type ClassRowsContainer = {
  _type: 'classRowsContainer'
  classRefs?: Array<
    {
      _key: string
    } & ClassReference
  >
}

export type ImageButtonCard = {
  _type: 'imageButtonCard'
  image?: MainImage
  heading: string
  copy?: SimplePortableText
  landingPageRoute?: PageReference
}

export type IconCard = {
  _type: 'iconCard'
  icon?: Icon
  heading: string
  copy?: SimplePortableText
  cta?: Cta
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heading?: string
  copy?: SimplePortableText
}

export type Resource = {
  _id: string
  _type: 'resource'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  fileDownload?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  ctaTitle?: string
  excerpt?: SimplePortableText
  image?: MainImage
}

export type Redirect = {
  _id: string
  _type: 'redirect'
  _createdAt: string
  _updatedAt: string
  _rev: string
  source: string
  destination: string
  permanent?: boolean
  description?: string
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heading: string
  price: number
  image?: MainImage
  cta?: Cta
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  seo?: Seo
  author: TrainerReference
  excerpt: SimplePortableText
  image?: MainImage
  subheader?: string
  body: MainPortableText
}

export type Trainer = {
  _id: string
  _type: 'trainer'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  picture: MainImage
  role?: string
  bio?: SimplePortableText
  certifications?: SimplePortableText
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Home = {
  _id: string
  _type: 'home'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  seo?: Seo
  content?: Array<
    | ({
        _key: string
      } & HeroBanner)
    | ({
        _key: string
      } & HeroTwoPanel)
    | ({
        _key: string
      } & SingleColumnContentBlock)
    | ({
        _key: string
      } & SuccessStoriesBlock)
    | ({
        _key: string
      } & RowContainer)
    | ({
        _key: string
      } & ProgramsGridContainer)
    | ({
        _key: string
      } & TrainersGridContainer)
    | ({
        _key: string
      } & TestimonialGridContainer)
    | ({
        _key: string
      } & ClassRowsContainer)
    | ({
        _key: string
      } & RelatedResourcesRow)
    | ({
        _key: string
      } & ContactPageMap)
    | ({
        _key: string
      } & CustomComponent)
    | ({
        _key: string
      } & ProductGridContainer)
  >
}

export type BlogLandingPage = {
  _id: string
  _type: 'blogLandingPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  seo?: Seo
  content?: Array<
    | ({
        _key: string
      } & HeroBanner)
    | ({
        _key: string
      } & HeroTwoPanel)
    | ({
        _key: string
      } & SingleColumnContentBlock)
    | ({
        _key: string
      } & SuccessStoriesBlock)
    | ({
        _key: string
      } & PostsGridContainer)
  >
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  menuItems?: Array<
    | ({
        _key: string
      } & NavCTA)
    | ({
        _key: string
      } & NavDropdownCTA)
    | {
        title: string
        slug: Slug
        seo?: Seo
        content?: Array<
          | ({
              _key: string
            } & HeroBanner)
          | ({
              _key: string
            } & HeroTwoPanel)
          | ({
              _key: string
            } & SingleColumnContentBlock)
          | ({
              _key: string
            } & SuccessStoriesBlock)
          | ({
              _key: string
            } & PostsGridContainer)
        >
        _type: 'blogLandingPage'
        _key: string
      }
  >
  footerLogos?: Array<
    {
      _key: string
    } & Logo
  >
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  seo?: Seo
  content?: Array<
    | ({
        _key: string
      } & HeroBanner)
    | ({
        _key: string
      } & HeroTwoPanel)
    | ({
        _key: string
      } & SingleColumnContentBlock)
    | ({
        _key: string
      } & SuccessStoriesBlock)
    | ({
        _key: string
      } & RowContainer)
    | ({
        _key: string
      } & ProgramsGridContainer)
    | ({
        _key: string
      } & TrainersGridContainer)
    | ({
        _key: string
      } & TestimonialGridContainer)
    | ({
        _key: string
      } & ClassRowsContainer)
    | ({
        _key: string
      } & RelatedResourcesRow)
    | ({
        _key: string
      } & ContactPageMap)
    | ({
        _key: string
      } & CustomComponent)
    | ({
        _key: string
      } & ProductGridContainer)
  >
}

export type Class = {
  _id: string
  _type: 'class'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  parentPage?: PageReference
  slug: Slug
  trainingType: 'group' | 'private' | 'onDemand'
  customTrainingTitle?: string
  price?: string
  upcomingClasses?: Array<
    {
      _key: string
    } & DateTimeV2
  >
  acuityCategoryUrl?: string
  takeaways?: Array<string>
  cardTakeaways?: Array<string>
  description?: SimplePortableText
  picture?: MainImage
  cardImage?: MainImage
  enhancedCardTitle?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | ContentBlock
  | SuccessStoriesBlock
  | SingleColumnContentBlock
  | RowContainer
  | PostReference
  | ResourceReference
  | RelatedResourcesRow
  | PageReference
  | ClassReference
  | SimplePortableText
  | SanityImageAssetReference
  | MainPortableText
  | Youtube
  | MainImage
  | LogoRow
  | Logo
  | Icon
  | HeroTwoPanel
  | HeroBanner
  | Form
  | Faq
  | SanityFileAssetReference
  | Cta
  | Carousel
  | AcuityForm
  | NavDropdownCTA
  | NavCTA
  | Seo
  | DateTimeV2
  | DateTime
  | TrainerReference
  | TrainersGridContainer
  | TestimonialReference
  | TestimonialGridContainer
  | ProgramsGridContainer
  | ProductReference
  | ProductGridContainer
  | PostsGridContainer
  | TrainerRows
  | GalleryGrid
  | CustomComponent
  | ContactPageMap
  | ContactInfo
  | AboutUsContainer
  | ClassRowsContainer
  | ImageButtonCard
  | IconCard
  | Testimonial
  | Resource
  | Redirect
  | Product
  | Post
  | Trainer
  | Slug
  | Home
  | BlogLandingPage
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | Class
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
